# Task-2 : Calcute Summary Statistics

# Import Packages

In [ ]:
import pandas as pd

# Reading Dataset

In [ ]:
data = pd.read_csv("/content/train.csv")

In [ ]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
data.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

# Information about the dataset

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
num_data= data.select_dtypes(include=['int64','float64'])
num_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [ ]:
num_data_columns=['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [ ]:
num_data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
series=pd.DataFrame(num_data)

In [ ]:
m=series[0:].median()
m

PassengerId    446.0000
Survived         0.0000
Pclass           3.0000
Age             28.0000
SibSp            0.0000
Parch            0.0000
Fare            14.4542
dtype: float64

In [ ]:
m=series[0:].mode()
m


PassengerId  Survived  Pclass   Age  SibSp  Parch  Fare
0              1       0.0     3.0  24.0    0.0    0.0  8.05
1              2       NaN     NaN   NaN    NaN    NaN   NaN
2              3       NaN     NaN   NaN    NaN    NaN   NaN
3              4       NaN     NaN   NaN    NaN    NaN   NaN
4              5       NaN     NaN   NaN    NaN    NaN   NaN
..           ...       ...     ...   ...    ...    ...   ...
886          887       NaN     NaN   NaN    NaN    NaN   NaN
887          888       NaN     NaN   NaN    NaN    NaN   NaN
888          889       NaN     NaN   NaN    NaN    NaN   NaN
889          890       NaN     NaN   NaN    NaN    NaN   NaN
890          891       NaN     NaN   NaN    NaN    NaN   NaN

[891 rows x 7 columns]

# Calculating Mean, Median, Mode.

In [ ]:
import numpy as np
from scipy.stats import mode

In [ ]:
mean1=np.mean(num_data,axis=0)
mean1

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [ ]:
median1=np.median(num_data,axis=0)
median1

array([446.    ,   0.    ,   3.    ,      nan,   0.    ,   0.    ,
        14.4542])

In [ ]:
for i in num_data_columns:
    print(i,data[i].mode())

Survived 0    0
Name: Survived, dtype: int64
Pclass 0    3
Name: Pclass, dtype: int64
Age 0    24.0
Name: Age, dtype: float64
SibSp 0    0
Name: SibSp, dtype: int64
Parch 0    0
Name: Parch, dtype: int64
Fare 0    8.05
Name: Fare, dtype: float64


In [ ]:
std_dev=np.std(num_data)
std_dev

PassengerId    257.209383
Survived         0.486319
Pclass           0.835602
Age             14.516321
SibSp            1.102124
Parch            0.805605
Fare            49.665534
dtype: float64

In [ ]:
variance=np.var(num_data)
variance

PassengerId    66156.666667
Survived           0.236506
Pclass             0.698231
Age              210.723580
SibSp              1.214678
Parch              0.648999
Fare            2466.665312
dtype: float64

In [ ]:
min_value=np.min(num_data,axis=0)
min_value

PassengerId    1.00
Survived       0.00
Pclass         1.00
Age            0.42
SibSp          0.00
Parch          0.00
Fare           0.00
dtype: float64

In [ ]:
max_value=np.max(num_data,axis=0)
max_value

PassengerId    891.0000
Survived         1.0000
Pclass           3.0000
Age             80.0000
SibSp            8.0000
Parch            6.0000
Fare           512.3292
dtype: float64

In [ ]:
percentiles_25=np.percentile(num_data,25,axis=0)
percentiles_25

array([223.5   ,   0.    ,   2.    ,      nan,   0.    ,   0.    ,
         7.9104])

In [ ]:
percentiles_50=np.percentile(num_data,50,axis=0)
percentiles_50

array([446.    ,   0.    ,   3.    ,      nan,   0.    ,   0.    ,
        14.4542])

In [ ]:
percentiles_75=np.percentile(num_data,75,axis=0)
percentiles_75

array([668.5,   1. ,   3. ,   nan,   1. ,   0. ,  31. ])